---
# This file is managed by the stacks toolchain. It may be overwritten by
# updates to the template. Your customizations should be placed inside the
# .kitchen.local.yml, which will not be overwritten by newer templates.
# If you need to override the driver, do it in ~/.kitchen/config.yml or using
# environment variables like VAGRANT_DEFAULT_PROVIDER.

driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 9200, host: 9200, auto_correct: true}] # elastic
  - ["forwarded_port", {guest: 443,   host: 8080, auto_correct: true}] # kibana

driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  client_rb:
    environment: _default
  attributes:
    cloud:
      public_ipv4: '127.0.0.1'
    authorization:
      sudo:
        users: ['vagrant']
        passwordless: true
    platformstack:
      cloud_backup:
        enabled: false
      cloud_monitoring:
        enabled: false
      omnibus_updater:
        enabled: false
    rackspace:
      cloud_credentials:
        username: 'racker'
        api_key: 'sekrit'

platforms:
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: centos-6.5
    run_list:
    - recipe[yum]

suites:
  - name: default
    run_list:
      - recipe[elkstack::java]
      - recipe[elkstack::single]
# remove rest until we get this working
#  - name: logstash_server
#    run_list: recipe[elkstack::logstash_server]
#  - name: kibana
#    run_list: recipe[elkstack::kibana]
